joy_launcher_node:
  ros__parameters:
    bindings:
      # - "3:ros2 launch duojin01_bringup mapping.launch.py"    # Y 键 -> 启动建图
      - "3:ros2 launch duojin01_bringup save_map.launch.py"          # Y 键 -> 保存地图
      # - "1:ros2 launch duojin01_bringup navigation.launch.py" # B 键 -> 启动导航
    hold_bindings:
      - "3:2.0"  # Y 键长按 2 秒触发保存
    trigger_feedback_buttons: [3]  # 触发时振动
    success_feedback_buttons: [3]  # 保存成功时振动
    feedback_topic: "/joy/set_feedback"
    trigger_feedback_intensity: 0.45
    trigger_feedback_duration_sec: 0.12
    success_feedback_intensity: 1.00
    success_feedback_duration_sec: 0.35
