#!/usr/bin/env bash
# bind_duojin01_devices.sh
# 用法：
#   sudo ./bind_duojin01_devices.sh /dev/ttyACM0 duojin01_controller "Controller"
#   sudo ./bind_duojin01_devices.sh /dev/ttyACM1 lslidar "Lslidar"

set -euo pipefail

DEV="${1:-}"
LINK="${2:-}"
LABEL="${3:-}"

RULES_FILE="/etc/udev/rules.d/99-duojin01-devlinks.rules"
GEN_TAG="# Auto-generated by bind_duojin01_devices.sh"

if [[ -z "$DEV" || -z "$LINK" ]]; then
  echo "Usage: sudo $0 </dev/ttyACM0|/dev/ttyUSB0> <symlink_name> [label]"
  exit 2
fi
if [[ ! -e "$DEV" ]]; then
  echo "Device not found: $DEV"
  exit 2
fi

props="$(udevadm info --query=property --name="$DEV" || true)"

get_prop() {
  local key="$1"
  echo "$props" | awk -F= -v k="$key" '$1==k{print $2; exit}'
}

ID_VENDOR_ID="$(get_prop ID_VENDOR_ID)"
ID_MODEL_ID="$(get_prop ID_MODEL_ID)"
ID_USB_DRIVER="$(get_prop ID_USB_DRIVER)"
ID_USB_INTERFACE_NUM="$(get_prop ID_USB_INTERFACE_NUM)"
ID_SERIAL_SHORT="$(get_prop ID_SERIAL_SHORT)"

if [[ -z "${ID_VENDOR_ID}" || -z "${ID_MODEL_ID}" || -z "${ID_SERIAL_SHORT}" ]]; then
  attrs="$(udevadm info -a -n "$DEV" 2>/dev/null || true)"
  [[ -z "${ID_VENDOR_ID}" ]] && ID_VENDOR_ID="$(echo "$attrs" | awk -F'=="' '/ATTRS\{idVendor\}==/{gsub(/"/,"",$2); print $2; exit}')"
  [[ -z "${ID_MODEL_ID}"  ]] && ID_MODEL_ID="$( echo "$attrs" | awk -F'=="' '/ATTRS\{idProduct\}==/{gsub(/"/,"",$2); print $2; exit}')"
  [[ -z "${ID_SERIAL_SHORT}" ]] && ID_SERIAL_SHORT="$(echo "$attrs" | awk -F'=="' '/ATTRS\{serial\}==/{gsub(/"/,"",$2); print $2; exit}')"
fi

need=(
  "ID_VENDOR_ID=$ID_VENDOR_ID"
  "ID_MODEL_ID=$ID_MODEL_ID"
  "ID_SERIAL_SHORT=$ID_SERIAL_SHORT"
)
for kv in "${need[@]}"; do
  if [[ "${kv#*=}" == "" ]]; then
    echo "Missing udev property: ${kv%%=*} (device: $DEV)"
    echo "Try: udevadm info --query=property --name=$DEV"
    exit 1
  fi
done

conds=('SUBSYSTEM=="tty"')
[[ -n "${ID_VENDOR_ID}" ]]        && conds+=("ENV{ID_VENDOR_ID}==\"${ID_VENDOR_ID}\"")
[[ -n "${ID_MODEL_ID}"  ]]        && conds+=("ENV{ID_MODEL_ID}==\"${ID_MODEL_ID}\"")
[[ -n "${ID_USB_DRIVER}" ]]       && conds+=("ENV{ID_USB_DRIVER}==\"${ID_USB_DRIVER}\"")
[[ -n "${ID_USB_INTERFACE_NUM}" ]] && conds+=("ENV{ID_USB_INTERFACE_NUM}==\"${ID_USB_INTERFACE_NUM}\"")
[[ -n "${ID_SERIAL_SHORT}" ]]     && conds+=("ENV{ID_SERIAL_SHORT}==\"${ID_SERIAL_SHORT}\"")

rule="$(IFS=', '; echo "${conds[*]}, SYMLINK+=\"${LINK}\", GROUP=\"dialout\", MODE=\"0660\"")"

sudo install -d -m 0755 "$(dirname "$RULES_FILE")"
if [[ ! -f "$RULES_FILE" ]]; then
  echo "$GEN_TAG" | sudo tee "$RULES_FILE" >/dev/null
fi
if ! sudo grep -qF "$GEN_TAG" "$RULES_FILE"; then
  echo "$GEN_TAG" | sudo tee -a "$RULES_FILE" >/dev/null
fi

if sudo grep -qE "SYMLINK\+?=\"${LINK}\"|SYMLINK\+\+=\"${LINK}\"|SYMLINK\+=\"${LINK}\"|SYMLINK\+=\"${LINK}\"" "$RULES_FILE"; then
  echo "Symlink '${LINK}' already exists in $RULES_FILE, skip."
  exit 0
fi

{
  echo ""
  if [[ -n "$LABEL" ]]; then
    echo "# ${LABEL} -> /dev/${LINK}"
  else
    echo "# ${LINK} -> /dev/${LINK}"
  fi
  echo "$rule"
} | sudo tee -a "$RULES_FILE" >/dev/null

sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=tty

echo "Appended to: $RULES_FILE"
echo "Now check: ls -l /dev/${LINK}"
