DEFAULT_CMD_VEL_TOPIC = '/cmd_vel'
DEFAULT_STAMPED = False
DEFAULT_FRAME_ID = ''

DEFAULT_LINEAR_SPEED = 0.3
DEFAULT_ANGULAR_SPEED = 0.3
DEFAULT_MAX_LINEAR_SPEED = 0.6
DEFAULT_MAX_ANGULAR_SPEED = 0.6
DEFAULT_LINEAR_SPEED_STEP = 0.05
DEFAULT_ANGULAR_SPEED_STEP = 0.1

ACCEL_LIMIT_LINEAR = 2.0
DECEL_LIMIT_LINEAR = 3.0
ACCEL_LIMIT_ANGULAR = 6.0
DECEL_LIMIT_ANGULAR = 8.0
DEFAULT_IDLE_TIMEOUT_SEC = 0.0

DEFAULT_PUBLISH_RATE = 120.0
DEFAULT_REPEAT_TIMEOUT_SEC = 0.50
DEFAULT_READ_POLL_TIMEOUT_SEC = 0.02
DEFAULT_TTY_DEVICE_PATH = ''


KEYBOARD_TELEOP_PARAMETER_DEFAULTS = {
    'cmd_vel_topic': DEFAULT_CMD_VEL_TOPIC,
    'stamped': DEFAULT_STAMPED,
    'frame_id': DEFAULT_FRAME_ID,
    'speed': DEFAULT_LINEAR_SPEED,
    'turn': DEFAULT_ANGULAR_SPEED,
    'max_speed': DEFAULT_MAX_LINEAR_SPEED,
    'max_turn': DEFAULT_MAX_ANGULAR_SPEED,
    'speed_step': DEFAULT_LINEAR_SPEED_STEP,
    'turn_step': DEFAULT_ANGULAR_SPEED_STEP,
    'publish_rate': DEFAULT_PUBLISH_RATE,
    'repeat_timeout_sec': DEFAULT_REPEAT_TIMEOUT_SEC,
    'read_poll_timeout': DEFAULT_READ_POLL_TIMEOUT_SEC,
    'tty_device_path': DEFAULT_TTY_DEVICE_PATH,
}


def keyboard_teleop_parameter_defaults() -> dict[str, bool | float | str]:
    return dict(KEYBOARD_TELEOP_PARAMETER_DEFAULTS)
